// Export a generated legal document (Markdown) to an editable Word (.doc) file
// or a PDF. jsPDF is dynamically imported so it never bloats the initial bundle.

type Block = { type: 'h1' | 'h2' | 'h3' | 'li' | 'p' | 'blank'; text: string };

function parseBlocks(md: string): Block[] {
    const lines = (md || '').replace(/\r\n/g, '\n').split('\n');
    const blocks: Block[] = [];
    for (const raw of lines) {
        const line = raw.trimEnd();
        if (!line.trim()) { blocks.push({ type: 'blank', text: '' }); continue; }
        let m: RegExpMatchArray | null;
        if ((m = line.match(/^###\s+(.*)/))) blocks.push({ type: 'h3', text: m[1] });
        else if ((m = line.match(/^##\s+(.*)/))) blocks.push({ type: 'h2', text: m[1] });
        else if ((m = line.match(/^#\s+(.*)/))) blocks.push({ type: 'h1', text: m[1] });
        else if ((m = line.match(/^\s*[-*]\s+(.*)/))) blocks.push({ type: 'li', text: m[1] });
        else if ((m = line.match(/^\s*\d+\.\s+(.*)/))) blocks.push({ type: 'li', text: m[1] });
        else blocks.push({ type: 'p', text: line });
    }
    return blocks;
}

const escapeHtml = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const inlineToHtml = (t: string) =>
    escapeHtml(t).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\*(.+?)\*/g, '<em>$1</em>');

const stripInline = (t: string) => t.replace(/\*\*/g, '').replace(/`/g, '');

const sanitizeFilename = (name: string) =>
    (name || 'document').replace(/[^\wሀ-፿ -]+/g, '').trim().replace(/\s+/g, '_').slice(0, 60) || 'document';

const DISCLAIMER = 'Generated by EthioLex — this is a draft. Review with a licensed Ethiopian lawyer before use.';

function triggerDownload(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function exportToWord(title: string, markdown: string) {
    const blocks = parseBlocks(markdown);
    let body = '';
    let inList = false;
    for (const b of blocks) {
        if (b.type === 'li') { if (!inList) { body += '<ul>'; inList = true; } body += `<li>${inlineToHtml(b.text)}</li>`; continue; }
        if (inList) { body += '</ul>'; inList = false; }
        if (b.type === 'h1') body += `<h1>${inlineToHtml(b.text)}</h1>`;
        else if (b.type === 'h2') body += `<h2>${inlineToHtml(b.text)}</h2>`;
        else if (b.type === 'h3') body += `<h3>${inlineToHtml(b.text)}</h3>`;
        else if (b.type === 'p') body += `<p>${inlineToHtml(b.text)}</p>`;
    }
    if (inList) body += '</ul>';

    const html =
        `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>` +
        `<head><meta charset='utf-8'><title>${escapeHtml(title)}</title>` +
        `<style>body{font-family:'Times New Roman',serif;font-size:12pt;line-height:1.5;color:#111;}` +
        `h1{font-size:16pt;text-align:center;margin:0 0 12pt;}h2{font-size:13pt;margin:14pt 0 6pt;}h3{font-size:12pt;margin:12pt 0 4pt;}` +
        `p{margin:0 0 10pt;}ul{margin:0 0 10pt 18pt;}</style></head>` +
        `<body>${body}<p style="margin-top:24pt;font-size:9pt;color:#666;font-style:italic;">${escapeHtml(DISCLAIMER)}</p></body></html>`;

    triggerDownload(new Blob(['﻿', html], { type: 'application/msword' }), sanitizeFilename(title) + '.doc');
}

export async function exportToPdf(title: string, markdown: string) {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const margin = 56;
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const maxW = pageW - margin * 2;
    let y = margin;

    const ensure = (h: number) => { if (y + h > pageH - margin) { doc.addPage(); y = margin; } };
    const write = (text: string, size: number, style: 'normal' | 'bold' | 'italic', gapAfter: number, align: 'left' | 'center' = 'left') => {
        doc.setFont('times', style);
        doc.setFontSize(size);
        const lineH = size * 1.45;
        for (const ln of doc.splitTextToSize(text, maxW)) {
            ensure(lineH);
            if (align === 'center') doc.text(ln, pageW / 2, y, { align: 'center' });
            else doc.text(ln, margin, y);
            y += lineH;
        }
        y += gapAfter;
    };

    doc.setTextColor(20);
    for (const b of parseBlocks(markdown)) {
        const text = stripInline(b.text);
        if (b.type === 'blank') { y += 6; continue; }
        if (b.type === 'h1') write(text, 16, 'bold', 10, 'center');
        else if (b.type === 'h2') write(text, 13, 'bold', 7);
        else if (b.type === 'h3') write(text, 12, 'bold', 5);
        else if (b.type === 'li') write('•  ' + text, 11, 'normal', 4);
        else write(text, 11, 'normal', 6);
    }

    ensure(28);
    doc.setTextColor(120);
    write(DISCLAIMER, 8, 'italic', 0);

    doc.save(sanitizeFilename(title) + '.pdf');
}
